version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stori"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = [
  "MailsFunction=590184066643.dkr.ecr.us-east-1.amazonaws.com/mails",
  "TransactionsFunction=590184066643.dkr.ecr.us-east-1.amazonaws.com/transactions",
]
