Resources:
  MailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Mails:
          Type: Api
          Properties:
            Path: /utils/mails
            Method: post
    Metadata:
      DockerTag: python3.9
      DockerContext: ./src/mails
      Dockerfile: Dockerfile
  TransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Transactions:
          Type: Api
          Properties:
            Path: /utils/transactions
            Method: post
      Environment:
        Variables:
          ENVIRONMENT: "local"
          DYNAMODB_URL: "http://host.docker.internal:8000"
          DYNAMODB_TABLE_NAME: "Transactions"
          AWS_DEFAULT_REGION: "us-east-1"
    Metadata:
      DockerTag: python3.9
      DockerContext: ./src/transactions
      Dockerfile: Dockerfile
